/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ReCaptcha_CONSTANTS_H
#define ReCaptcha_CONSTANTS_H

#include "ReCaptcha_types.h"



class ReCaptchaConstants {
 public:
  ReCaptchaConstants();

  int32_t RECAPTCHA_MESSAGE_FONT_CENTER_SCAN;
  int32_t RECAPTICHA_MESSAGE_FONT_CENTER_SCAN_INDEX;
  int32_t RECAPTICHA_MESSAGE_FONT_CENTER_SCAN_INDEX_FEEDBACK;
};

extern const ReCaptchaConstants g_ReCaptcha_constants;



#endif
