/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
 #ifdef _WIN32
#include "StdAfx.h"
#endif
#include "ReCaptcha_constants.h"



const ReCaptchaConstants g_ReCaptcha_constants;

ReCaptchaConstants::ReCaptchaConstants() {
  RECAPTCHA_MESSAGE_FONT_CENTER_SCAN = 100000;

  RECAPTICHA_MESSAGE_FONT_CENTER_SCAN_INDEX = 100001;

  RECAPTICHA_MESSAGE_FONT_CENTER_SCAN_INDEX_FEEDBACK = 100002;

}



